#!/bin/bash

HOSTNAME="localhost"
PORT=8080
SIZE=1

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -h|-host)
            HOSTNAME="$2"
            shift 2
        ;;
        -p|-port)
            PORT="$2"
            shift 2
        ;;
        -n|-np)
            SIZE="$2"
            shift 2
        ;;
        *)
            POSITIONAL+=("$1")
            shift
        ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [ -z $1 ]; then
    echo -e "mympirun a.out\n"
    echo "Arguments:"
    echo "-h <host>"
    echo "    - Name of host on which to run processes"
    echo "-p <port>"
    echo "    - Port on which to run processes"
    echo "-n <np>"
    echo "    - Specify the number of processes to use"
else
    for (( i=0; i < $SIZE; ++i )); do
        ./$1 $HOSTNAME $PORT $i $SIZE &
    done  
fi